# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project01+20241120\Image_Viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Image_show(object):
    def setupUi(self, Image_show):
        Image_show.setObjectName("Image_show")
        Image_show.resize(1115, 796)
        Image_show.setMouseTracking(True)
        Image_show.setSizeGripEnabled(True)

        self.retranslateUi(Image_show)
        QtCore.QMetaObject.connectSlotsByName(Image_show)

    def retranslateUi(self, Image_show):
        _translate = QtCore.QCoreApplication.translate
        Image_show.setWindowTitle(_translate("Image_show", "Image Viewer"))
